contact_links:
  - name: My account got banned!
    url: https://github.com/masa-finance/td-masa-fork/blob/main/.github/SUPPORT.md#how-not-to-get-banned
    about: 'Use "How not to get banned" guide'
  - name: Ask on Telegram (Russian)
    url: https://t.me/gotd_ru
    about: You can ask for help in Russian here!
  - name: Ask on Telegram (English)
    url: https://t.me/gotd_en
    about: You can ask for help in English here!
  - name: Ask on GitHub
    url: https://github.com/masa-finance/td-masa-fork/discussions/new?category=q-a
    about: You can ask for help without using Telegram too!
  - name: Want to contribute to gotd?
    url: https://github.com/masa-finance/td-masa-fork/blob/main/CONTRIBUTING.md
    about: Be sure to read contributing guidelines!
